### ISSUE TITLE
用ctex编译报错

### ISSUE THREAD

**Issue by kli-casia** [phoenix1917/CASIA-Thesis#1]
![qq 20180307094138](https://user-images.githubusercontent.com/13194870/37068852-c6dee3b6-21eb-11e8-84de-c5d222d30012.png)

**Comment by phoenix1917** [comment]
CTeX 宏集到 2.x 版本才支持 \ctexset 语法，检查一下你的宏包版本？

**Comment by raysworld** [comment]
UCAS-Thesis那边推荐用texlive，如果ctex始终报错可以换一下

**Comment by kli-casia** [comment]
换成 texlive之后，问题解决了，thx

**Comment by phoenix1917** [comment]
CTeX需要额外安装宏包，另外目前官网提供的CTeX下载里的WinEdt已经过期了。各人环境配置上可能有差别，CTeX环境我再调试一下。
Mac环境直接装TeXShop就可以，它的宏包是texlive。
