### ISSUE TITLE
Minor difference in format

### ISSUE THREAD

**Issue by raysworld** [phoenix1917/CASIA-Thesis#2]
1. 请问所有格式要求都是以“中国科学院大学研究生学位论文撰写规范指导意见-调整修订格式版-2018.1.25-修改.doc”这个文件为准吗？国科大网站上也有一些关于格式的说明，如http://onestop.ucas.edu.cn/home/info/abc167cb-4589-4e05-b014-052fa9291d0c/1提供了封面的格式，但和上述doc文件有一些区别，是否都已上述doc文件为准？
2. 如是，在中文封面页，关于指导教师一栏，doc文件提供的样张是有两行的，是否应第一行填写姓名和专业技术职务，第二行填写工作单位？（可能是考虑到某些情况下指导教师和学生培养单位不在同一单位？）

**Comment by phoenix1917** [comment]
一般导师都是自己所里的所以不写，不写的情况下不会渲染出那一行。如果你有这样的需求，在配置文件里有一个第二导师栏位，也可以写职务信息。

**Comment by raysworld** [comment]
明白了，谢谢！😊

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
